name: Deploy to SFTP

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Upload via SFTP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          source: "."
          target: "/portfolio"
